name: Debug

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    container:
      image: babashka/babashka:alpine

    steps:
      - name: Install tools and run
        run: |
          set -eux

          apk add --no-cache git curl skopeo

          COSIGN_VERSION="v2.2.4"
          curl -L -o /usr/local/bin/cosign \
            https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64
          chmod +x /usr/local/bin/cosign

          # Clone the public repo you want to check
          git clone --no-single-branch https://github.com/ublue-os/bluefin.git bluefin
          cd bluefin
          git fetch --tags --force

          # Optional: debug tags
          git tag

          # Run your Babashka script from your sandbox
          bb ../repo/changelog.clj stable-20260212 stable-20260217 dk187-changelog.md

          # Copy artifact for GitHub Actions
          cp dk187-changelog.md /dk187-changelog.md

      - uses: actions/upload-artifact@v4
        with:
          name: dk187-changelog
          path: dk187-changelog.md
