name: Debug

on:
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    container:
      image: babashka/babashka:alpine

    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache git skopeo curl

          # Install cosign
          COSIGN_VERSION="v2.2.4"
          curl -L -o /usr/local/bin/cosign \
            https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64
          chmod +x /usr/local/bin/cosign

      - uses: actions/checkout@v4

      - name: Generate changelog
        run: bb changelog.clj stable-20260212 stable-20260217 dk187-changelog.md

      - uses: actions/upload-artifact@v4
        with:
          name: dk187-changelog
          path: dk187-changelog.md
